### ISSUE TITLE
Requirements not installable

### ISSUE THREAD

**Issue by bottest123** [b-fg/nuatsbot#1]
Hello 

The requirements.txt is not updated and there are 2-3 python modules which are not installable coz the pip command cannot find any module of that name..
The code exame is below when I ran pip3 install -r requirements.txt

![screenshot_2018-10-15-14-52-22-127](https://user-images.githubusercontent.com/41206183/46941985-f7208280-d089-11e8-9dff-5dfc97265cf2.jpeg)

Help...

**Comment by b-fg** [comment]
Hi! Thanks for reporting the issue. I have now fixed the requirements.txt and it should work. Please let me know if you still have problems.

**Comment by b-fg** [comment]
Closed since the user could finally install the requirements with the latest requirements.txt update.
