### ISSUE TITLE
Bug while running nuats_bot.py 

### ISSUE THREAD

**Issue by peterabj** [b-fg/nuatsbot#11]
0%|          | 0/4 [00:00<?, ?it/s]C:\Users\dell\PycharmProjects\nuatsbot\venv\lib\site-packages\sklearn\linear_model\_base.py:141: FutureWarning: 'normalize' was deprecated in version 1.0 and will be removed in 1.2.
If you wish to scale the data, use Pipeline with a StandardScaler in a preprocessing stage. To reproduce the previous behavior:

from sklearn.pipeline import make_pipeline

model = make_pipeline(StandardScaler(with_mean=False), LinearRegression())

If you wish to pass a sample_weight parameter, you need to pass it as a fit parameter to each step of the pipeline as follows:

kwargs = {s[0] + '__sample_weight': sample_weight for s in model.steps}
model.fit(X, y, **kwargs)

  warnings.warn(
C:\Users\dell\PycharmProjects\nuatsbot\venv\lib\site-packages\sklearn\linear_model\_base.py:141: FutureWarning: 'normalize' was deprecated in version 1.0 and will be removed in 1.2.
If you wish to scale the data, use Pipeline with a StandardScaler in a preprocessing stage. To reproduce the previous behavior:

from sklearn.pipeline import make_pipeline

model = make_pipeline(StandardScaler(with_mean=False), LinearRegression())

If you wish to pass a sample_weight parameter, you need to pass it as a fit parameter to each step of the pipeline as follows:

kwargs = {s[0] + '__sample_weight': sample_weight for s in model.steps}
model.fit(X, y, **kwargs)

  warnings.warn(
C:\Users\dell\PycharmProjects\nuatsbot\venv\lib\site-packages\sklearn\linear_model\_base.py:141: FutureWarning: 'normalize' was deprecated in version 1.0 and will be removed in 1.2.
If you wish to scale the data, use Pipeline with a StandardScaler in a preprocessing stage. To reproduce the previous behavior:

from sklearn.pipeline import make_pipeline

model = make_pipeline(StandardScaler(with_mean=False), LinearRegression())

If you wish to pass a sample_weight parameter, you need to pass it as a fit parameter to each step of the pipeline as follows:

kwargs = {s[0] + '__sample_weight': sample_weight for s in model.steps}
model.fit(X, y, **kwargs)

  warnings.warn(
C:\Users\dell\PycharmProjects\nuatsbot\venv\lib\site-packages\sklearn\linear_model\_base.py:141: FutureWarning: 'normalize' was deprecated in version 1.0 and will be removed in 1.2.
If you wish to scale the data, use Pipeline with a StandardScaler in a preprocessing stage. To reproduce the previous behavior:

from sklearn.pipeline import make_pipeline

model = make_pipeline(StandardScaler(with_mean=False), LinearRegression())

If you wish to pass a sample_weight parameter, you need to pass it as a fit parameter to each step of the pipeline as follows:

kwargs = {s[0] + '__sample_weight': sample_weight for s in model.steps}
model.fit(X, y, **kwargs)

  warnings.warn(
C:\Users\dell\PycharmProjects\nuatsbot\venv\lib\site-packages\sklearn\linear_model\_base.py:141: FutureWarning: 'normalize' was deprecated in version 1.0 and will be removed in 1.2.
If you wish to scale the data, use Pipeline with a StandardScaler in a preprocessing stage. To reproduce the previous behavior:

from sklearn.pipeline import make_pipeline

model = make_pipeline(StandardScaler(with_mean=False), LinearRegression())

If you wish to pass a sample_weight parameter, you need to pass it as a fit parameter to each step of the pipeline as follows:

kwargs = {s[0] + '__sample_weight': sample_weight for s in model.steps}
model.fit(X, y, **kwargs)

  warnings.warn(
C:\Users\dell\PycharmProjects\nuatsbot\venv\lib\site-packages\sklearn\linear_model\_base.py:141: FutureWarning: 'normalize' was deprecated in version 1.0 and will be removed in 1.2.
If you wish to scale the data, use Pipeline with a StandardScaler in a preprocessing stage. To reproduce the previous behavior:

from sklearn.pipeline import make_pipeline

model = make_pipeline(StandardScaler(with_mean=False), LinearRegression())

If you wish to pass a sample_weight parameter, you need to pass it as a fit parameter to each step of the pipeline as follows:

kwargs = {s[0] + '__sample_weight': sample_weight for s in model.steps}
model.fit(X, y, **kwargs)

  warnings.warn(
C:\Users\dell\PycharmProjects\nuatsbot\venv\lib\site-packages\sklearn\linear_model\_base.py:141: FutureWarning: 'normalize' was deprecated in version 1.0 and will be removed in 1.2.
If you wish to scale the data, use Pipeline with a StandardScaler in a preprocessing stage. To reproduce the previous behavior:

from sklearn.pipeline import make_pipeline

model = make_pipeline(StandardScaler(with_mean=False), LinearRegression())

If you wish to pass a sample_weight parameter, you need to pass it as a fit parameter to each step of the pipeline as follows:

kwargs = {s[0] + '__sample_weight': sample_weight for s in model.steps}
model.fit(X, y, **kwargs)

  warnings.warn(
C:\Users\dell\PycharmProjects\nuatsbot\venv\lib\site-packages\sklearn\linear_model\_base.py:141: FutureWarning: 'normalize' was deprecated in version 1.0 and will be removed in 1.2.
If you wish to scale the data, use Pipeline with a StandardScaler in a preprocessing stage. To reproduce the previous behavior:

from sklearn.pipeline import make_pipeline

model = make_pipeline(StandardScaler(with_mean=False), LinearRegression())

If you wish to pass a sample_weight parameter, you need to pass it as a fit parameter to each step of the pipeline as follows:

kwargs = {s[0] + '__sample_weight': sample_weight for s in model.steps}
model.fit(X, y, **kwargs)

  warnings.warn(
 25%|██▌       | 1/4 [00:00<00:01,  1.56it/s]
Traceback (most recent call last):
  File "C:\Users\dell\PycharmProjects\nuatsbot\nuats_bot.py", line 124, in <module>
    main()
  File "C:\Users\dell\PycharmProjects\nuatsbot\nuats_bot.py", line 112, in main
    tickers_TA_list =  list(tqdm(executor.map(TA_task, a), total=len(a)))
  File "C:\Users\dell\PycharmProjects\nuatsbot\venv\lib\site-packages\tqdm\std.py", line 1195, in __iter__
    for obj in iterable:
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.1520.0_x64__qbz5n2kfra8p0\lib\concurrent\futures\_base.py", line 609, in result_iterator
    yield fs.pop().result()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.1520.0_x64__qbz5n2kfra8p0\lib\concurrent\futures\_base.py", line 439, in result
    return self.__get_result()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.1520.0_x64__qbz5n2kfra8p0\lib\concurrent\futures\_base.py", line 391, in __get_result
    raise self._exception
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.1520.0_x64__qbz5n2kfra8p0\lib\concurrent\futures\thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "C:\Users\dell\PycharmProjects\nuatsbot\nuats_bot.py", line 49, in TA_task
    klines = bclient.get_last_klines(ticker, interval, n_periods)
  File "C:\Users\dell\PycharmProjects\nuatsbot\binance_client\client.py", line 289, in get_last_klines
    return self.get_klines(
  File "C:\Users\dell\PycharmProjects\nuatsbot\binance_client\client.py", line 197, in get_klines
    return self._get('klines', data = params)
  File "C:\Users\dell\PycharmProjects\nuatsbot\binance_client\client.py", line 104, in _get
    return self._request_api('get', path, **kwargs)
  File "C:\Users\dell\PycharmProjects\nuatsbot\binance_client\client.py", line 89, in _request_api
    return self._request(method, uri, **kwargs)
  File "C:\Users\dell\PycharmProjects\nuatsbot\binance_client\client.py", line 85, in _request
    return self._handle_response(response)
  File "C:\Users\dell\PycharmProjects\nuatsbot\binance_client\client.py", line 97, in _handle_response
    raise BinanceAPIException(response)
binance_client.exceptions.BinanceAPIException: APIError(code=-1120): Invalid interval.

**Comment by b-fg** [comment]
Pleas make the effort of correctly explain the problem encountered, not just copy-pasting an error output.

**Comment by peterabj** [comment]
Hi, first of all thanks for your help. 
What I did is download your code in PyCharm , checked the requirements (everything was downloaded), added the needed values to config.py  , then ran the code(nuats_bot.py), this is the error that I got.

**Comment by b-fg** [comment]
It looks like the interval you are querying is not possible in Binance, double check this.

```
File "C:\Users\dell\PycharmProjects\nuatsbot\binance_client\client.py", line 97, in _handle_response
raise BinanceAPIException(response)
binance_client.exceptions.BinanceAPIException: APIError(code=-1120): Invalid interval.
```

**Comment by peterabj** [comment]
Hi. 
I fixed Binance's  interval. 
I am still receiving  an error from sklearn. (check the attached file for all the returned error + output)
though I am receiving a message in my discord saying Signals : (Picture)
[nuats bot error.txt](https://github.com/b-fg/nuatsbot/files/9226969/nuats.bot.error.txt)
![Screenshot 2022-07-30 200740](https://user-images.githubusercontent.com/102736128/181934242-c2e8a08f-28ad-4b9b-b430-81fbb6432c49.png)

**Comment by b-fg** [comment]
These are warnings, not errors. The only thing happening is that there are no signals, according to the query you are sending to Binance. Try to set a more general query, and then you should get signals on that.

**Comment by peterabj** [comment]
I tried to add more tickers and intervals nothing happened 
any suggestion for a configuration 
(got this error)
[2nd run.txt](https://github.com/b-fg/nuatsbot/files/9240417/2nd.run.txt)

![nos](https://user-images.githubusercontent.com/102736128/182328971-9195b6e8-039d-47d3-8156-170193304eb8.png)

**Comment by b-fg** [comment]
Try to `tickers = []` to query over all pairs, and use a lower number of periods, like `1000`. You might get some signals like this, just to verify it works.

**Comment by peterabj** [comment]
Thank you for your help.
Everything is going so smoothly, great bot.
