### ISSUE TITLE
Problem with receiving signals

### ISSUE THREAD

**Issue by justemerald** [b-fg/nuatsbot#12]
Hello!
I have a problem with receiving signals.
When I launch the bot, it only writes the word Signal to me but does not write other data.
What should I do?
Thank you!
<img width="764" alt="Снимок экрана 2022-08-15 в 22 23 42" src="https://user-images.githubusercontent.com/93739049/184703368-e31ec78a-695b-494e-b5ae-6b4c2ae9df86.png">

**Comment by b-fg** [comment]
It just looks like there are no signals with the parameters you have set up. In the `congif.py` file, try `tickers = []` to query over all pairs, and `n_periods = 1000`. Otherwise copy-paste here you `config.py` file and I will have a look at it.

**Comment by justemerald** [comment]
kline = dict(tickers = ['BTCUSDT'],       
             intervals = ['1m'],    
             n_periods = 500,       
             start_time = '15 Aug, 2022',       
             end_time = '16 Aug, 2022')         

live_bot = dict(live = False,             
                sleep = 20,                    
                threading = True,              
                telegram_token = '****************************',          
                telegram_chat_id = ['**********'],      
                discord_web_hook = [''])      

P.S. * - for my privacy

**Comment by b-fg** [comment]
But have you tried what I said?

**Comment by justemerald** [comment]
Thank you very much for the quick reply!
It helps me.
But I got a new error:
<img width="1152" alt="Снимок экрана 2022-08-16 в 09 21 57" src="https://user-images.githubusercontent.com/93739049/184811435-06302e61-5d35-431b-81f8-c2648a4ca140.png">

**Comment by b-fg** [comment]
You just exceeded the number of requests to Binance. Try using a larger value for sleep if you are in the `live` bot mode.
