### ISSUE TITLE
The Telegram broadcasting system is not working

### ISSUE THREAD

**Issue by bottest123** [b-fg/nuatsbot#2]
I set up the config.py added my telegram bit token and channel ID 
But it doesn't work...

My config.py 

https://user-images.githubusercontent.com/41206183/46945089-8a10eb00-d091-11e8-8b16-59c34cea5272.jpeg

It says Telegram Broadcasting ['channelid'] and stops but nothing happens see below code

https://user-images.githubusercontent.com/41206183/46945102-9432e980-d091-11e8-9483-6a030eeb2a9b.png

https://user-images.githubusercontent.com/41206183/46945112-9a28ca80-d091-11e8-8801-dbaf2f566d6b.jpeg

What's the prob?please help

**Comment by b-fg** [comment]
First, since it seems that it is already working for you after you just opened #1, I will close #1.
Second, I do not know why is your bot not reporting the signals in Telegram. It works well with my Telegram bot token and my Telegram chat id. Please double check that both values are correct and that your bot has admin rights in the channel.

**Comment by bottest123** [comment]
Ya it sent it and how to schedule it to send it every 2 mins?

**Comment by bottest123** [comment]
How to schedule it for every 2 mins?

**Comment by b-fg** [comment]
> How to schedule it for every 2 mins?

Please keep the issues reporting clean and create new issues now that this has been solved.

**Comment by bottest123** [comment]
> > How to schedule it for every 2 mins?
> 
> Please keep the issues reporting clean and create new issues now that this has been solved.

Done

**Comment by b-fg** [comment]
> > > How to schedule it for every 2 mins?
> > 
> > 
> > Please keep the issues reporting clean and create new issues now that this has been solved.
> 
> Done

I do not see your new issue, if you have submitted one.
