### ISSUE TITLE
A minimalisitc RSI signal script with open api

### ISSUE THREAD

**Issue by bluetyphoon77** [b-fg/nuatsbot#9]
Hi ;)
I was searching for examples of little bots using free api's rather than binance or any exchange where kyc is needed.
I would love to ask you, how many lines would it take to write a script just printing a signal when BTCUSDT weekly RSI reached a specific level ? I'm a beginner and I would love to start with the most minimalistic script possible using Ta-lib or open API.
Would you be able to help ? I'd be ok to pay you for the writing of those lines... Please keep in touch ;)
thanks in advance

**Comment by b-fg** [comment]
Hi,

What do you mean by free API? Nuatsbot is currently able to get the weekly RSI of the BTUSDT pair in Binance as you described. For other exchanges, you would need to change the [binance_client](https://github.com/b-fg/nuatsbot/tree/master/binance_client) for a different client complying with the exchange API. Feel free to email me and we can chat about it :)

Cheers,

Bernat

**Comment by bluetyphoon77** [comment]
Hi Bernat, thanks a lot for your answer
Do we then need to have our own API to provide from our Binance account ?
ok i email you too for other ideas ;) thanks
